- name: "Install {{ shell }}"
  become: yes
  become_method: sudo
  package:
    name: "{{ shell }}"

- name: "Configure {{ username }}'s shell to be {{ shell }}"
  when: username|default(None) != None
  user:
    name: "{{ username }}"
    shell: "{{ shell }}"
