- name: Install shell
  become: yes
  package:
    name: "{{ shell.pkg }}"

- name: Configure user's shell
  when: user|default(None) != None
  user:
    name: "{{ user }}"
    shell: "{{ shell.bin }}"
