language: python

services:
  - docker

env:
  - PLAYBOOK=gateway.yml
  - PLAYBOOK=htpc.yml
  - PLAYBOOK=lan.yml
  # - PLAYBOOK=local-desktop.yml
  - PLAYBOOK=optiplex.yml
  - PLAYBOOK=workstation.yml

install:
  - make install

script:
  - make
