- name: LAN playbook
  hosts:
    - sandbox
  roles:
    - { role: run-as, tags: common, become: yes }
    # - { role: hostname, tags: hostname }
    - { role: common, tags: common, become: yes }
    - { role: full-upgrade, tags: upgrade, become: yes }
    # - { role: ssh-key, tags: ssh-key }

- hosts: gateway
  vars:
    - username: "{{ ansible_user }}"
  roles:
    # - { role: hostname, tags: hostname, become: yes }
    - { role: common, tags: common, become: yes }
    - { role: full-upgrade, tags: upgrade, become: yes }
    # - { role: ssh-key, tags: ssh-key }
    - { role: wifi, tags: wifi, become: yes }
    - { role: shell, tags: shell, become: yes }
    - { role: dotfiles, tags: dotfiles }

- hosts: optiplex
  become: yes
  gather_facts: yes
  vars:
    - username: "{{ ansible_user }}"
  roles:
    # - { role: hostname, tags: hostname, become: yes }
    - { role: common, tags: common, become: yes }
    - { role: full-upgrade, tags: upgrade, become: yes }
    # - { role: ssh-key, tags: ssh-key }
    # - { role: sudo, tags: sudo, become: yes }
    - { role: ssh-server, tags: ssh-server, become: yes }
    - { role: dell, tags: dell, become: yes }
    - { role: dotfiles, tags: dotfiles }
    - { role: shell, tags: shell }
    - { role: prezto, tags: prezto }

- hosts: htpc
  roles:
    # - { role: hostname, become: yes, become_method: sudo, tags: hostname }
    - { role: common, tags: common, become: yes }
    - { role: gui, tags: gui, become: yes }
    - { role: kodi, tags: kodi, become: yes }
  tasks:
    - name: Install workstation packages
      become: yes
      tags: ["apt"]
      apt:
        name: "{{ item }}"
      with_items:
        - solaar # Logitech Unify
        - openssh-server

    # - name: Install snap packages
    #   snap:
    #     name: "{{ item }}"
    #     classic: yes
    #   with_items:
    #     - code-insiders
    #     - chromium
    #     - slack
    #     - spotify

    # - name: "Git clone Prezto for current user: {{ansible_user_id }}"
    #   git:
    #     repo: https://github.com/sorin-ionescu/prezto.git
    #     dest: "/home/{{ ansible_user_id }}/.zprezto"

    # - name: Install Prezto
    #   file:
    #     path: "/home/{{ ansible_user_id }}/.{{ item }}"
    #     src: "/home/{{ ansible_user_id }}/.zprezto/runcoms/{{ item }}"
    #     state: link
    #     mode: 0644
    #   with_items:
    #       - zlogin
    #       - zlogout

    # - name: "Git clone dotfiles for current user:  {{ ansible_user_id }}"
    #   git:
    #     repo: "{{ dotfiles_repo_url }}"
    #     dest: "/home/{{ ansible_user_id }}/.dotfiles"
    #     accept_hostkey: True
    #   register: dotfiles_repo

    # - name: Symlink dotfiles
    #   command: "/home/{{ ansible_user_id }}/.dotfiles/dotfiles.sh link"
    #   when: dotfiles_repo.changed

    # - name: Change shell to zsh
    #   become: yes
    #   user:
    #     name: "{{ ansible_user_id }}"
    #     shell: /bin/zsh

    # - name: Cutomize Nautilus sidebar
    #   tags: nautilus
    #   lineinfile:
    #     dest: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
    #     regexp: "^{{ item }}"
    #     state: absent
    #   with_items:
    #     - XDG_TEMPLATES_DIR
    #     - XDG_PUBLICSHARE_DIR
    #     - XDG_DOCUMENTS_DIR
    #     - XDG_MUSIC_DIR
    #     - XDG_PICTURES_DIR
    #     - XDG_VIDEOS_DIR
