- hosts: localhost
  vars:
    - username: "{{ ansible_user }}"
  roles:
    - { role: common, become: yes }
    - ssh-key
    - { role: docker, become: yes }

  tasks:
    - name: Install workstation packages
      become: yes
      tags: apt
      package:
        name: "{{ item }}"
        update_cache: yes
        state: latest
        force: yes
      with_items:
        - zsh
        - xbindkeys
        - xautomation
        - terminator
        - krb5-user # for work
        - python3-venv
        - python3-pip
        - solaar # Logitech Unify
        - ruby # Chef
        - ruby-dev
        - zlib1g-dev
        - openssh-server
        - fonts-powerline
        - git-review
        - ipmitool
        - powerwake
        - jq
        - tig
        - iperf3
        - sipcalc
        - ack

    # - name: Remove deprecated packages
    #   tags: apt
    #   apt:
    #     name: "{{ item }}"
    #     state: absent
    #     autoremove: yes
    #     autoclean: yes
    #   with_items:
    #     - None

    # - name: Install snap packages
    #   snap:
    #     name: "{{ item }}"
    #     classic: yes
    #   with_items:
    #     - code-insiders
    #     - chromium
    #     - slack
    #     - spotify

    - name: Retrieve Powerline font families
      tags: fonts
      git:
        repo: https://github.com/powerline/fonts.git
        dest: /tmp/powerline-fonts
        depth: 1
    
    - name: Install Powerline font families
      tags: fonts
      shell: /tmp/powerline-fonts/install.sh
      args:
        creates: "{{ ansible_user_dir }}.local/share/fonts"

    - name: "Git clone Prezto for current user: {{ansible_user_id }}"
      git:
        repo: https://github.com/sorin-ionescu/prezto.git
        dest: "{{ ansible_user_dir }}/.zprezto"
        depth: 1
    
    - name: Install Prezto
      file:
        path: "{{ ansible_user_dir }}/.{{ item }}"
        src: "{{ ansible_user_dir }}/.zprezto/runcoms/{{ item }}"
        state: link
        mode: 0644
      with_items:
          - zlogin
          - zlogout

    - name: "Git clone dotfiles for current user:  {{ ansible_user_id }}"
      git:
        repo: "{{ dotfiles_repo_url }}"
        dest: "{{ ansible_user_dir }}/.dotfiles"
        accept_hostkey: True
      register: dotfiles_repo
    
    - name: Symlink dotfiles
      command: "{{ ansible_user_dir }}/.dotfiles/dotfiles.sh link"
      when: dotfiles_repo.changed

    - name: Change shell to zsh
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Create Terminator config directory
      tags: nord
      file:
        path: "{{ ansible_user_dir }}/.config/terminator"
        state: directory

    - name: Add Terminator Nord theme
      tags: nord
      get_url:
        dest: "{{ ansible_user_dir }}/.config/terminator/config"
        url: https://raw.githubusercontent.com/arcticicestudio/nord-terminator/develop/src/config
        force: yes

    - name: Add Dbeaver GPG key
      become: yes
      apt_key:
        url: https://dbeaver.io/debs/dbeaver.gpg.key

    - name: Add Dbeaver repository
      become: yes
      apt_repository:
        repo: deb https://dbeaver.io/debs/dbeaver-ce /

    - name: Install Dbeaver
      become: yes
      apt:
        name: dbeaver-ce
        update_cache: yes
        state: latest

    - name: Add Google Chrome GPG key
      become: yes
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub

    - name: Add Google Chrome repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome

    - name: Install Google Chrome
      become: yes
      apt:
        name: google-chrome-beta
        update_cache: yes
        state: latest

    - name: Add Nvidia repository
      become: yes
      apt_repository:
        repo: 'ppa:graphics-drivers'

    - name: Install Nvidia driver
      become: yes
      apt:
        name: nvidia-driver-430 # check latest version first: https://www.nvidia.com/object/unix.html
        update_cache: yes

    - name: Create Kerberos conf folders for Chrome/Chromium
      become: yes
      file:
        path: "{{ item }}"
        state: directory
        mode: 0644
        recurse: yes
      with_items:
        - /etc/opt/chrome/policies/managed
        - /etc/chromium-browser/policies/managed

    - name: Add Kerberos conf to Chrome/Chromium
      become: yes
      copy:
        dest: "{{ item }}"
        mode: 0644
        force: yes
        content: |
          {
            "AuthServerWhitelist": ".hpc.criteo.prod, .hpc.criteo.preprod, .criteois.com",
            "AuthNegotiateDelegateWhitelist": ".hpc.criteo.prod, .hpc.criteo.preprod, .criteois.com"
          }
      with_items:
        - /etc/opt/chrome/policies/managed/criteo.json
        - /etc/chromium-browser/policies/managed/criteo.json

    - name: Download Dropbox
      tags: dropbox
      command: "wget -O /tmp/dropbox.tar.gz \"https://www.dropbox.com/download?plat=lnx.x86_64\""
      args:
        creates: "{{ ansible_user_dir }}/.dropbox-dist/"
      register: download_dropbox
    
    - name: Extract Dropbox
      tags: dropbox
      unarchive:
        src: /tmp/dropbox.tar.gz
        dest: "{{ ansible_user_dir }}"
      when: download_dropbox.changed

    - name: Start Dropbox
      tags: dropbox
      command: "echo \"Dropbox new install, please execute {{ ansible_user_dir }}/.dropbox-dist/dropboxd\""
      when: download_dropbox.changed

    - name: Add Dropbox autostart
      tags:
        - dropbox
        - ignore
      copy:
        dest: "{{ ansible_user_dir }}/.config/autostart/dropboxd.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Exec={{ ansible_user_dir }}/.dropbox-dist/dropboxd
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Name[en_US]=Dropbox
          Name=Dropbox
          Comment[en_US]=Dropbox
          Comment=Dropbox

    - name: Install OneDrive client
      tags: onedrive
      become: yes
      apt:
        name: onedrive
      register: install_onedrive

    - name: "Instructions, documentation: https://github.com/abraunegg/onedrive"
      tags:
        - onedrive
        - ignore
      become: yes
      command: systemctl --user enable onedrive && systemctl --user start onedrive
      when: install_onedrive.changed

    - name: Multiple screen Gnome workspaces
      command: gsettings set org.gnome.mutter workspaces-only-on-primary false

    - name: Cutomize Nautilus sidebar
      tags:
        - nautilus
        - ignore
      lineinfile:
        dest: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
        regexp: "^{{ item }}"
        state: absent
      with_items:
        - XDG_TEMPLATES_DIR
        - XDG_PUBLICSHARE_DIR
        - XDG_DOCUMENTS_DIR
        - XDG_MUSIC_DIR
        - XDG_PICTURES_DIR
        - XDG_VIDEOS_DIR

          #    - name: Install Kite
          #      tags: ignore
          #      shell: bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
          #      args:
          #        creates: "{{ ansible_user_dir }}/.local/share/kite/"

    # - name: Display paths of all .txt files in dir
    #   tags: firefox
    #   debug:
    #     msg: "{{ lookup('fileglob', '{{ ansible_user_dir }}/.mozilla/firefox/vyi8ui1k.default/*.js') }}"

    # - name: Set DNS resolver for Firefox
    #   # tags: firefox
    #   replace:
    #     path: "{{ lookup('fileglob', '{{ ansible_user_dir }}/.mozilla/firefox/*/prefs2.js') }}') }}"
    #     regexp: "^user_pref(\"{{ item.key }}\", (.*))$"
    #     replace: "{{ item.value }}"
    #   with_dict:
    #     - network.trr.bootstrapAddress: 5.182.208.0
    #     - network.trr.custom_uri: "https://dns.nextdns.io/8936ab"
    #     - network.trr.mode: 3
    #     - network.trr.uri: "https://dns.nextdns.io/8936ab"

# ln -s ~/Dropbox/Pictures/Simple\ Desktops ~/Pictures/Wallpapers

# Ruby / Chef
# gem install bundler
# bundle update --bundler
# https://github.com/abraunegg/onedrive

# mkdir -p ~/.gradle/init.d && curl -o ~/.gradle/init.d/criteo-init.gradle http://moab-filer.crto.in/scripts/criteo-init.gradle
