- hosts: localhost

  tasks:
    - name: Install workstation packages
      become: yes
      tags: ["apt"]
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
        force: yes
      with_items:
        - vim
        - git
        - zsh
        - htop
        - curl
        - wget
        - xbindkeys
        - xautomation
        - terminator
        - fonts-powerline

    # - name: Install snap packages
    #   snap:
    #     name: "{{ item }}"
    #     classic: yes
    #   with_items:
    #     - code-insiders
    #     - chromium
    #     - slack
    #     - spotify
    
    - name: "Git clone Prezto for current user: {{ansible_user_id }}"
      git:
        repo: https://github.com/sorin-ionescu/prezto.git
        dest: "/home/{{ ansible_user_id }}/.zprezto"
    
    - name: Install Prezto
      file:
        path: "/home/{{ ansible_user_id }}/.{{ item }}"
        src: "/home/{{ ansible_user_id }}/.zprezto/runcoms/{{ item }}"
        state: link
        mode: 0644
      with_items:
          - zlogin
          - zlogout
    
    - name: "Git clone dotfiles for current user:  {{ ansible_user_id }}"
      git:
        repo: "{{ dotfiles_repo_url }}"
        dest: "/home/{{ ansible_user_id }}/.dotfiles"
        accept_hostkey: True
      register: dotfiles_repo
    
    - name: Symlink dotfiles
      command: "/home/{{ ansible_user_id }}/.dotfiles/dotfiles.sh link"
      when: dotfiles_repo.changed

    - name: Change shell to zsh
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Install Docker requirements
      become: yes
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
        force: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      
    - name: "Add Docker repository for {{ ansible_distribution_release }}"
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Install Docker
      become: yes
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
        force: yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
