- hosts:
    - localhost
    - workstation
  vars:
    - username: "{{ ansible_user }}"
  roles:
    - { role: hostname, tags: hostname, become: yes }
    - { role: common, tags: common, become: yes }
    - { role: python, tags: python }
    - { role: ssh-server, tags: ssh, become: yes }
    - { role: ssh-key, tags: ssh-key }
    - { role: shell, tags: shell }
    - { role: gui-apps, tags: gui, become: yes }
    - { role: keyboard-mouse, tags: [keyboard, mouse], become: yes }
    - { role: prompt, tags: prompt}
    # - { role: docker, tags: docker, become: yes }
    # - { role: work-tools, tags: work, become: yes }
    # - { role: user/dropbox }

  tasks:
    # - name: Install snap packages
    #   snap:
    #     name: "{{ item }}"
    #     classic: yes
    #   with_items:
    #     - code-insiders
    #     - chromium
    #     - slack
    #     - spotify

    # - name: Add Dbeaver GPG key
    #   become: yes
    #   apt_key:
    #     url: https://dbeaver.io/debs/dbeaver.gpg.key

    # - name: Add Dbeaver repository
    #   become: yes
    #   apt_repository:
    #     repo: deb https://dbeaver.io/debs/dbeaver-ce /

    # - name: Install Dbeaver
    #   become: yes
    #   apt:
    #     name: dbeaver-ce
    #     update_cache: yes
    #     state: latest

    # - name: Add Google Chrome GPG key
    #   become: yes
    #   apt_key:
    #     url: https://dl-ssl.google.com/linux/linux_signing_key.pub

    # - name: Add Google Chrome repository
    #   become: yes
    #   apt_repository:
    #     repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    #     filename: google-chrome

    # - name: Install Google Chrome
    #   become: yes
    #   apt:
    #     name: google-chrome-beta
    #     update_cache: yes
    #     state: latest

    # - name: Add Nvidia repository
    #   tags: driver
    #   become: yes
    #   apt_repository:
    #     repo: 'ppa:graphics-drivers'

    # - name: Install Nvidia driver
    #   tags: driver
    #   become: yes
    #   apt:
    #     name: nvidia-driver-440 # check latest version first: https://www.nvidia.com/object/unix.html
    #     update_cache: yes

    # - name: Create Kerberos conf folders for Chrome/Chromium
    #   become: yes
    #   file:
    #     path: "{{ item }}"
    #     state: directory
    #     mode: 0644
    #     recurse: yes
    #   with_items:
    #     - /etc/opt/chrome/policies/managed
    #     - /etc/chromium-browser/policies/managed

    # - name: Add Kerberos conf to Chrome/Chromium
    #   become: yes
    #   copy:
    #     dest: "{{ item }}"
    #     mode: 0644
    #     force: yes
    #     content: |
    #       {
    #         "AuthServerWhitelist": ".hpc.criteo.prod, .hpc.criteo.preprod, .criteois.com",
    #         "AuthNegotiateDelegateWhitelist": ".hpc.criteo.prod, .hpc.criteo.preprod, .criteois.com"
    #       }
    #   with_items:
    #     - /etc/opt/chrome/policies/managed/criteo.json
    #     - /etc/chromium-browser/policies/managed/criteo.json

    # - name: Install OneDrive client
    #   tags: onedrive
    #   become: yes
    #   apt:
    #     name: onedrive
    #   register: install_onedrive

    # - name: "Instructions, documentation: https://github.com/abraunegg/onedrive"
    #   tags:
    #     - onedrive
    #     - ignore
    #   become: yes
    #   systemd:
    #     name: onedrive
    #     state: started
    #     enabled: yes
    #     scope: user
    #   when: install_onedrive.changed

    # - name: Multiple screen Gnome workspaces
    #   command: gsettings set org.gnome.mutter workspaces-only-on-primary false

    # - name: Cutomize Nautilus sidebar
    #   tags:
    #     - nautilus
    #     - ignore
    #   lineinfile:
    #     dest: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
    #     regexp: "^{{ item }}"
    #     state: absent
    #   with_items:
    #     - XDG_TEMPLATES_DIR
    #     - XDG_PUBLICSHARE_DIR
    #     - XDG_DOCUMENTS_DIR
    #     - XDG_MUSIC_DIR
    #     - XDG_PICTURES_DIR
    #     - XDG_VIDEOS_DIR

          #    - name: Install Kite
          #      tags: ignore
          #      shell: bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
          #      args:
          #        creates: "{{ ansible_user_dir }}/.local/share/kite/"

    # - name: Display paths of all .txt files in dir
    #   tags: firefox
    #   debug:
    #     msg: "{{ lookup('fileglob', '{{ ansible_user_dir }}/.mozilla/firefox/vyi8ui1k.default/*.js') }}"

    # - name: Set DNS resolver for Firefox
    #   # tags: firefox
    #   replace:
    #     path: "{{ lookup('fileglob', '{{ ansible_user_dir }}/.mozilla/firefox/*/prefs2.js') }}') }}"
    #     regexp: "^user_pref(\"{{ item.key }}\", (.*))$"
    #     replace: "{{ item.value }}"
    #   with_dict:
    #     - network.trr.bootstrapAddress: 5.182.208.0
    #     - network.trr.custom_uri: "https://dns.nextdns.io/8936ab"
    #     - network.trr.mode: 3
    #     - network.trr.uri: "https://dns.nextdns.io/8936ab"

# ln -s ~/Dropbox/Pictures/Simple\ Desktops ~/Pictures/Wallpapers

# Ruby / Chef
# gem install bundler
# bundle update --bundler
# https://github.com/abraunegg/onedrive

# mkdir -p ~/.gradle/init.d && curl -o ~/.gradle/init.d/criteo-init.gradle http://moab-filer.crto.in/scripts/criteo-init.gradle
