- hosts: opx
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    - username: "{{ ansible_user }}"
  roles:
    - { role: hostname, tags: [hostname] }
    - { role: package-upgrade, tags: [upgrade] }
    - { role: sudo, tags: [sudo] }
    - { role: common, tags: [common] }
    - { role: ssh-server, tags: [ssh-server] }
    - { role: dell, tags: [dell] }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: ssh-key, tags: [ssh-key] }
    - { role: password, tags: [password] }
    - { role: zsh, tags: [zsh] }
    - { role: prezto, tags: [prezto] }
