- hosts: all

  tasks:
    - name: Install workstation packages
      become: yes
      tags: ["apt"]
      apt:
          name: "{{ item }}"
          update_cache: yes
          state: latest
          force: yes
      with_items:
        - htop
        # - tar
        # - unzip
        # - python
