- hosts: workstation
  gather_facts: no
  tasks:
    - name: "Start test container"
      delegate_to: localhost
      docker_container:
        name: "{{ inventory_hostname }}"
        image: "{{ docker_image }}"
        command: sleep 30m
        state: started
        recreate: yes
        cleanup: yes
        detach: true
        interactive: true
        tty: true

    - name: Install python and sudo inside the container
      raw: apt -y update && apt install -y python3-minimal python3-urllib3 sudo

- name: Import local-desktop.yml playbook
  import_playbook: local-desktop.yml

- name: Idempotency check of local-desktop.yml playbook
  import_playbook: local-desktop.yml

- hosts: workstation
  tasks:
    - name: "Stop {{ inventory_hostname }} container"
      delegate_to: localhost
      docker_container:
        name: "{{ inventory_hostname }}"
        state: absent
