- name: Git clone Prezto
  become: yes
  become_user: "{{ user }}"
  when: username|default(None) != None
  git:
    repo: "{{ prezto_repo_url }}"
    version: master
    dest: "/home/{{ user }}/.zprezto"
    accept_hostkey: yes
    clone: yes
    update: yes
    depth: 1
