- name: Git clone Prezto
  become_user: "{{ username }}"
  when: username|default(None) != None
  git:
    repo: "{{ prezto_repo_url }}"
    dest: "/home/{{ username }}/.zprezto"
    accept_hostkey: yes
    clone: yes
    update: yes
