- name: "Git clone dotfiles for current user: {{ ansible_user_id }}"
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ ansible_user_dir }}/.dotfiles"
    version: master
    accept_hostkey: True
  notify: Symlink dotfiles

