- name: "Git clone dotfiles for current user: {{ ansible_user_id }}"
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ ansible_user_dir }}/.dotfiles"
    accept_hostkey: True
  register: dotfiles_repo

- name: Symlink dotfiles
  command: "{{ ansible_user_dir }}/.dotfiles/dotfiles.sh link"
  when: dotfiles_repo.changed
