- name: Git clone dotfiles
  when: username|default(None) != None and dotfiles_repo_url|default(None) != None
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "/home/{{ username }}/.dotfiles"
    accept_hostkey: yes
    clone: yes
    update: yes

- name: Link dotfiles
  shell: "/home/{{ username }}/.dotfiles/dotfiles.sh link"
  args:
    creates: "/home/{{ username }}/.zshrc"
