- name: Git clone dotfiles
  when: username|default(None) != None and dotfiles_repo_url|default(None) != None
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "/home/{{ username }}/.dotfiles"
    accept_hostkey: yes
    clone: yes
    update: yes
  register: dotfiles_clone

- name: Link dotfiles
  when: dotfiles_clone.changed
  shell: "/home/{{ username }}/.dotfiles/dotfiles.sh link"
