- name: Set Kodi autostart
  file:
    dest: ~/.config/autostart/
    state: directory
    recurse: yes

- name: Set Kodi autostart
  copy:
    dest: ~/.config/autostart/kodi.desktop
    content: >
      [Desktop Entry]
      Type=Application
      Exec=/usr/bin/kodi
      Hidden=false
      NoDisplay=false
      X-GNOME-Autostart-enabled=true
      Name[en_US]=Kodi
      Name=Kodi
      Comment[en_US]=Kodi
      Comment=Kodi
