- name: Define LOCALES environment variables
  become: yes
  become_method: sudo
  lineinfile:
      dest: "/etc/environment"
      line: "{{ item }}"
      state: present
      create: yes
  with_items:
    - export LC_ALL=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
