- name: Install basic packages
  package:
    name: "{{ item }}"
  with_items:
    - ack
    - curl
    - fzf
    - htop
    - iftop
    - iperf3
    - jq
    - mosh
    - ncdu
    - nmap
    - nmon
    - sipcalc
    - tmux
    - tree
    - vim
    - wget

- name: Install Git tools
  package:
    name: "{{ item }}"
  with_items:
    - git
    - tig
    - git-review
