- name: Install basic packages
  become: yes
  become_method: sudo
  package:
    name: "{{ item }}"
  with_items:
    - git
    - htop
    - iftop
    - nmap
    - nmon
    - iperf
    - tmux
    - tree
    - vim
    - wget
    - screen
    - curl
    - ncdu
    - tree
