- name: Install basic packages
  package:
    name: "{{ item }}"
  with_items:
    - curl
    - git
    - htop
    - iftop
    - iperf
    - ncdu
    - nmap
    - nmon
    - tmux
    - tree
    - vim
    - wget
    - mosh
    - fzf
