name: Mac OS

on:
  push:
    paths:
    - 'mac-os-x/*'

jobs:
  macos:
    name: Local test on macos
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Brewfile
        run: brew bundle install mac-os-x/Brewfile
