name: Mac OS

on: [push]

#on:
#  push:
#    paths:
#    - '.github/*'
#    - 'mac-os-x/*'

jobs:
  macos:
    name: Install Mac OS Homebrew packages
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install Brewfile
        run: brew bundle install --file=mac-os/Brewfile
